// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// redatam.cpp
sexp read_redatam_(strings dic_path_in);
extern "C" SEXP _redatam_read_redatam_(SEXP dic_path_in) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_redatam_(cpp11::as_cpp<cpp11::decay_t<strings>>(dic_path_in)));
  END_CPP11
}
// rindexing.cpp
sexp bin_get_rvector(sexp bin, sexp indices);
extern "C" SEXP _redatam_bin_get_rvector(SEXP bin, SEXP indices) {
  BEGIN_CPP11
    return cpp11::as_sexp(bin_get_rvector(cpp11::as_cpp<cpp11::decay_t<sexp>>(bin), cpp11::as_cpp<cpp11::decay_t<sexp>>(indices)));
  END_CPP11
}
// rindexing.cpp
sexp pck_get_rvector(sexp pck, sexp indices);
extern "C" SEXP _redatam_pck_get_rvector(SEXP pck, SEXP indices) {
  BEGIN_CPP11
    return cpp11::as_sexp(pck_get_rvector(cpp11::as_cpp<cpp11::decay_t<sexp>>(pck), cpp11::as_cpp<cpp11::decay_t<sexp>>(indices)));
  END_CPP11
}
// rindexing.cpp
sexp chr_get_rvector(sexp chr, sexp indices);
extern "C" SEXP _redatam_chr_get_rvector(SEXP chr, SEXP indices) {
  BEGIN_CPP11
    return cpp11::as_sexp(chr_get_rvector(cpp11::as_cpp<cpp11::decay_t<sexp>>(chr), cpp11::as_cpp<cpp11::decay_t<sexp>>(indices)));
  END_CPP11
}
// rindexing.cpp
sexp int_get_rvector(sexp intg, sexp indices);
extern "C" SEXP _redatam_int_get_rvector(SEXP intg, SEXP indices) {
  BEGIN_CPP11
    return cpp11::as_sexp(int_get_rvector(cpp11::as_cpp<cpp11::decay_t<sexp>>(intg), cpp11::as_cpp<cpp11::decay_t<sexp>>(indices)));
  END_CPP11
}
// rindexing.cpp
sexp lng_get_rvector(sexp lng, sexp indices);
extern "C" SEXP _redatam_lng_get_rvector(SEXP lng, SEXP indices) {
  BEGIN_CPP11
    return cpp11::as_sexp(lng_get_rvector(cpp11::as_cpp<cpp11::decay_t<sexp>>(lng), cpp11::as_cpp<cpp11::decay_t<sexp>>(indices)));
  END_CPP11
}
// rindexing.cpp
sexp real_get_rvector(sexp real, sexp indices);
extern "C" SEXP _redatam_real_get_rvector(SEXP real, SEXP indices) {
  BEGIN_CPP11
    return cpp11::as_sexp(real_get_rvector(cpp11::as_cpp<cpp11::decay_t<sexp>>(real), cpp11::as_cpp<cpp11::decay_t<sexp>>(indices)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_redatam_bin_get_rvector",  (DL_FUNC) &_redatam_bin_get_rvector,  2},
    {"_redatam_chr_get_rvector",  (DL_FUNC) &_redatam_chr_get_rvector,  2},
    {"_redatam_int_get_rvector",  (DL_FUNC) &_redatam_int_get_rvector,  2},
    {"_redatam_lng_get_rvector",  (DL_FUNC) &_redatam_lng_get_rvector,  2},
    {"_redatam_pck_get_rvector",  (DL_FUNC) &_redatam_pck_get_rvector,  2},
    {"_redatam_read_redatam_",    (DL_FUNC) &_redatam_read_redatam_,    1},
    {"_redatam_real_get_rvector", (DL_FUNC) &_redatam_real_get_rvector, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_redatam(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
