// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// Rexports.cpp
list read_redatam_(std::string dic_path_in);
extern "C" SEXP _readredatam_read_redatam_(SEXP dic_path_in) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_redatam_(cpp11::as_cpp<cpp11::decay_t<std::string>>(dic_path_in)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_readredatam_read_redatam_", (DL_FUNC) &_readredatam_read_redatam_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_readredatam(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
