# Generated by cpp11: do not edit by hand

read_redatam_ <- function(dic_path_in) {
  .Call(`_redatam_read_redatam_`, dic_path_in)
}

bin_get_rvector <- function(bin, indices) {
  .Call(`_redatam_bin_get_rvector`, bin, indices)
}

pck_get_rvector <- function(pck, indices) {
  .Call(`_redatam_pck_get_rvector`, pck, indices)
}

chr_get_rvector <- function(chr, indices) {
  .Call(`_redatam_chr_get_rvector`, chr, indices)
}

int_get_rvector <- function(intg, indices) {
  .Call(`_redatam_int_get_rvector`, intg, indices)
}

lng_get_rvector <- function(lng, indices) {
  .Call(`_redatam_lng_get_rvector`, lng, indices)
}

real_get_rvector <- function(real, indices) {
  .Call(`_redatam_real_get_rvector`, real, indices)
}
