# Generated by cpp11: do not edit by hand

create_dummy_df_ <- function() {
  .Call(`_readredatam_create_dummy_df_`)
}

read_redatam_ <- function(dicx_file) {
  .Call(`_readredatam_read_redatam_`, dicx_file)
}
